# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xEbb6fUEfpkEJ2Ppdah1Um2xN4LwbJch
"""

def squares(start, end):
	return [ n*n for n in range(start, end+1) ]
print(squares(0,10))

year = int(input('Enter year : '))

if (year%4 == 0 and year%100 != 0) or (year%400 == 0) :
    print(year, "is a leap year.")
else :
    print(year, "is not a leap year.")

array = [1,2,3,4,5,6]

def even(array):
	new_array = []
	for i in array:
		if i%2==0:
			new_array.append(i)
	return new_array

print(even(array))

array1=[1,2,3,4,5]
array2=[2,4,6,8,9]
def filter(array1,array2):
  for i in array1:
    for j in array2:
       if i==j:
         print(i)

filter(array1,array2)

myList=[10,20,30,'apple',True,8,10]
myList.append(30)
myList.append(40)
length=len(myList)
reversedList=[]
for i in myList:
    reversedList.append(myList[length-1])
    length-=1
print(reversedList)

myDict={1:"data",2:"information",3:"text"}
myDict.pop(3)
myDict[3]="features"
for i in myDict:
  if myDict[i]=="data":
    print(myDict[i])

my_tuple=(1, 2, 3, 'apple', 'mango')
print(my_tuple)

numeric_tuple =(10, 20, 30, 40, 50)

min(numeric_tuple)

r1=my_tuple+numeric_tuple
print(r1)

newdupli=r1*2
print(newdupli)

my_tuple=(1, 2, 3, 'apple', 'mango')
print(my_tuple)
min(numeric_tuple)
r1=my_tuple+numeric_tuple
print(r1)
newdupli=r1*2
print(newdupli)

set1={1,2,3,4,5}
set2={2,3,7,6,1}
print("set1 U set2:", set1.union(set2))
print(set1.intersection(set2))
print(set1.difference(set2))

a=10
b=20
if(a>b):
  print("a is greater")
if(a<b):
  print("b is greater")

print('Numbers from 1 to 10:')
n = 1
while n <= 10:
   print(n, end=' ')
   n = n+1

i = 1
while(i<=10):
    print(i,end=" ")
    i += 1

num1, num2, num3 = 10 , 30 , 20
max = 0
if num1 >= num2 and num1 >= num3:
  print(num1)
elif num2 >= num1 and num2 >= num3:
  print(num2)
else:
  print(num3)

list1=[10,23,4,26,4,75,24,54]
num = 0
while(num < len(list1)):
    if list1[num] % 2 == 0:
        print(list1[num], end=" ")
    num += 1

lower_value = int(input ("Please, Enter the Lowest Range Value: "))
upper_value = int(input ("Please, Enter the Upper Range Value: "))

print ("The Prime Numbers in the range are: ")
for number in range (lower_value, upper_value + 1):
    if number > 1:
        for i in range (2, number):
            if (number % i) == 0:
                break
        else:
            print (number,end=" ")

